import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display, Inter, Great_Vibes, Sansita_Swashed, Lobster  } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Providers from "@/components/Providers";

// const sansitaSwashed = Sansita_Swashed ({
//   subsets: ["latin"],
//   weight: ["400","700"]
// });
const lobster = Lobster ({
  subsets: ["latin"],
  weight : "400",
  variable:"--font-lobster"
});


const greatVibes = Great_Vibes ({
  subsets: ["latin"],
  weight : "400",
  variable:"--font-great-vibes",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nsuk Nest",
  description: "Generated by create next app",
};

export default function RootLayout({
   children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${greatVibes.variable} ${playfair.variable} ${lobster.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
        <Navbar/>
        {children}
        <Footer/>
        </Providers>
        
        </body>
    </html>
  );
} 
